version: '3'
services:
  app:
    build: .
    tty: true
    volumes:
      # ここでマウントしておくと、ホストのファイルがコンテナ内に反映されるのは自明だが
      # コンテナ内でファイルを変更する(ex) package.jsonの更新・新しくファイル作るなど)時も
      # ホスト側に変更が反映される
      - ../node-docker:/app

# 以上の設定で、コンテナ内に入ればnodeの環境で開発できる。
# ホストマシンの環境を汚さずにすむ
